[package]
name = "ghostylab-mondev"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"]  

[dependencies.rocket]
version = "0.5.1"
features = ["json"]
